Set required Python version >= 2.7.10.
Python versions < 2.7.9 have SSL certificate problems that can cause
clients to reject valid server certificates.

cf. http://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

This manifests as:
```
In [5]: print("Found {} PIFs in dataset {}".format(client.search(query_dataset).total_num_hits, dataset_id))
/home/maxhutch/anaconda2/lib/python2.7/site-packages/requests-2.10.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/maxhutch/anaconda2/lib/python2.7/site-packages/requests-2.10.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
...
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```